__DICT_EXCLUSIONS_SALARY_LIKE_FP__ = {
    "keywords_exclude_contain": [
        "point of sale",
        "return",
        "reversal",
        "cancel",
        "correction",
        "rtn",
        "lottery",
        "interest",
        "mobile deposit",
        "mobile cheque",
        "pts frm",
        "treas"
    ],
    "keywords_exclude_exact": [
        "pos"
    ],
    "keywords_replace_empty": [
        "electronic funds transfer",
        "internet banking",
        "internet deposit",
        "internet transfer",
        "branch transaction",
        "transaction",
        "purchase",
        "payment",
        "miscellaneous",
        "depositfree",
        "autodeposit",
        "deposit",
        "etransfer",
        "transfer",
        "online banking",
        "debit",
        "etrnsfr ad",
        "etrnsfr",
        "recvd",
        "vopay international",
        "credit memo",
        "credit",
        "paypal"
    ],
    "keywords_replace_empty_exact": [
        "eft",
        "interac",
        "jan",
        "feb",
        "mar",
        "apr",
        "may",
        "jun",
        "jul",
        "aug",
        "sep",
        "oct",
        "nov",
        "dec",
        "vopay",
        "misc",
        "tf",
        "msp"
    ]
}
