__DICT_CATEGORIES_GENERAL_CONTAINED__ = {
    "is_obligation": [
        "loan",
        "lending",
        "line of credit",
        "credit line",
        "afterpay",
        "progressivelease",
        "snap finance",
        "mintomoney",
        "best egg"
    ],
    "is_mortgage": [
        "mortg",
        "mtg"
    ],
    "is_payday": [
        "earninact",
        "navchek",
        "moneylion",
        "advancecash",
        "dave inc",
        "davecom",
        "payactiv",
        "instacash",
        "cashnetusa",
        "check n go",
        "oportun",
        "lendup",
        "check into cash",
        "silver cloud"
    ],
    "is_education": [
        "education",
        "student",
        "preschool"
    ],
    "is_salary": [
        "payroll",
        "salary"
    ],
    "is_taxes": [
        "tax"
    ],
    "is_benefit": [
        "benef",
        "income life",
        "child support"
    ],
    "is_fee": [
        "fee",
        "atm rebate",
        "service charge",
        "insufficient funds charge",
        "overdraft"
    ],
    "is_transfer": [
        "cash appcash",
        "from chk",
        "save as you go",
        "tfr to",
        "tfr frm",
        "eb to",
        "eb from",
        "transfer",
        "trnsfr"
    ],
    "is_cash": [
        "cash ewithdrawal",
        "cash deposit",
        "branch deposit",
        "cash disbursed"
    ],
    "is_investment": [
        "savings",
        "money market",
        "investm",
        "robinhood",
        "etrade",
        "stash capital"
    ],
    "is_retirement": [
        "401k",
        "pension",
        "retirement"
    ],
    "is_purchase": [
        "point of sale"
    ],
    "is_gambling": [
        "betting",
        "casino",
        "sportsbook",
        "poker",
        "draftkings",
        "betmgm",
        "fanduel",
        "betrivers",
        "sugarhouse",
        "unibet"
    ],
    "is_usual": [
        "mcdonald",
        "chickfila",
        "vending",
        "wendys",
        "taco bell",
        "burger king",
        "little caesars",
        "popeyes",
        "subway",
        "starbucks",
        "applecom",
        "family dollar",
        "walmart",
        "7 eleven",
        "amazon",
        "shell",
        "walgreens",
        "netflix"
    ],
    "is_business_loan": [
        "ebf holdings",
        "amex",
        "mca servicing",
        "forward financin",
        "cfg merchant",
        "vader",
        "mantisfund",
        "the fundworks",
        "fundbox",
        "retail capital",
        "national funding",
        "ondeck",
        "expansioncapital",
        "sbfs",
        "forwardfinancing",
        "global funding",
        "mckenzie capital",
        "delta bridge fun",
        "kap",
        "kalamata",
        "knight capital",
        "green capital",
        "last chance fund",
        "pearl capital",
        "silverline servi",
        "newco cap",
        "on deck",
        "reliant funding",
        "lg funding",
        "greenbox capital",
        "mulligan senior",
        "fleetcor funding",
        "ffs",
        "flexibility cap",
        "bluevine",
        "snap advances",
        "itria ven",
        "premier capital",
        "gotorro",
        "reliant spv",
        "mcs",
        "fora financial",
        "gfe holdings",
        "capital advance",
        "wide merchant",
        "vitalcap",
        "samson horus",
        "cancapital",
        "clearfund",
        "advance service",
        "yes lender",
        "elevate funding",
        "rbrglobal",
        "iou central",
        "mbfs",
        "vox funding",
        "businessbacker",
        "tandem advance",
        "westwoodfunding",
        "elevation capita",
        "millstone",
        "advancemerc",
        "apex capital",
        "unique funding",
        "fundamental cap",
        "edgecap",
        "channel partners",
        "cardiff",
        "prosperum",
        "byzfunder ny",
        "premium merchant",
        "hfh cap",
        "cooper asset",
        "lendora",
        "rival fund",
        "kabbage",
        "wellen capital",
        "ml factors",
        "kodiak funding",
        "fundr",
        "liquidibee",
        "good funding",
        "ufs",
        "lendr",
        "forwardline",
        "capytal com",
        "wisefunding",
        "fundo",
        "ironwood finance",
        "biz fund",
        "lendingclub",
        "flash advance",
        "gem funding",
        "irm capital",
        "pirs capital",
        "libertasfunding",
        "diverse capital",
        "ims fund",
        "broadway advance",
        "cml",
        "brownstone fund",
        "ar capital",
        "rivalfund",
        "iruka capital",
        "efinancialtree",
        "ace funding",
        "qfscapital",
        "uplyft capital",
        "reliable fast",
        "loanme",
        "global merchant",
        "caymus funding",
        "avanza capital",
        "pdm capital",
        "simply funding",
        "advance merchant",
        "fundfi",
        "mr advance",
        "apex funding",
        "novus capital",
        "favo funding",
        "custom capital",
        "balboa capital",
        "st source advis",
        "capital dude",
        "pacwestern",
        "roc funding",
        "hi bar cap",
        "velocity cap",
        "fivetower",
        "highspeedcap",
        "everydaycap",
        "merchant capital",
        "surfside capital",
        "american funds",
        "rdm capital",
        "bluebridgecap",
        "mantis fund",
        "breakout cap",
        "ocean funding",
        "lendingpoint",
        "phoenix capital group",
        "cedar advance",
        "ibex funding",
        "simply equities",
        "first down",
        "river advance",
        "direct funding",
        "diesel funding",
        "amerifi capital",
        "syndimate",
        "sprout fun",
        "splashadvance",
        "gcm capital",
        "amsterdamcap",
        "rbs capital",
        "jolt funding",
        "sbf finance",
        "sos capital",
        "blue sky",
        "everyday capital",
        "high speed capit"
    ],
    "is_consumer_loan": [
        "ace cash express",
        "american web loa",
        "arrowheadadvance",
        "availblue",
        "avail blue",
        "avant llc",
        "bigpictureloans",
        "big picture loan",
        "bison green",
        "blueriver",
        "bluetrustloans",
        "eloanwarehouse",
        "bridge lending s",
        "brightlending cr",
        "brightlending debcred",
        "cash advance now",
        "vbs creditcube",
        "vbs eagle valley",
        "earnin pay",
        "earninactiveh",
        "elevate funding",
        "enova loc",
        "evergreen se",
        "foxhills",
        "gateway financ",
        "golden valley le",
        "greentrustcash",
        "inbox loan db",
        "jetcredit",
        "lakeshorelns",
        "lendgreen",
        "lendingclub",
        "lending club",
        "lendumo",
        "lightstream loan",
        "little lake lend",
        "littlelake ppd",
        "lone star cash",
        "vbs luckystar",
        "mitigcapital",
        "mountain summit msf",
        "netpay advance",
        "net pay advance",
        "oxford financial",
        "plain green llc cr",
        "plain green llc descr",
        "radiant cash",
        "ready set go",
        "redwood coast fi",
        "rise de ii cr",
        "silver cloud fin",
        "skytrail",
        "sky trail",
        "vbs solid oak",
        "spotloan cr",
        "spotloan debit",
        "spotloan db",
        "stonelakelending",
        "tan oak lending",
        "target cash now",
        "the loansmith",
        "upgrade inc",
        "uprova",
        "upstart",
        "zfunds",
        "zocaloans",
        "zoca loans"
    ]
}
