__DICT_STATES_US__ = {"ALABAMA": "AL",
                        "ALASKA": "AK",
                        "ARIZONA": "AZ",
                        "ARKANSAS": "AR",
                        "CALIFORNIA": "CA",
                        "COLORADO": "CO",
                        "CONNECTICUT": "CT",
                        "DELAWARE": "DE",
                        "FLORIDA": "FL",
                        "GEORGIA": "GA",
                        "HAWAII": "HI",
                        "IDAHO": "ID",
                        "ILLINOIS": "IL",
                        "INDIANA": "IN",
                        "IOWA": "IA",
                        "KANSAS": "KS",
                        "KENTUCKY": "KY",
                        "LOUISIANA": "LA",
                        "MAINE": "ME",
                        "MARYLAND": "MD",
                        "MASSACHUSETTS": "MA",
                        "MICHIGAN": "MI",
                        "MINNESOTA": "MN",
                        "MISSISSIPPI": "MS",
                        "MISSOURI": "MO",
                        "MONTANA": "MT",
                        "NEBRASKA": "NE",
                        "NEVADA": "NV",
                        "NEW HAMPSHIRE": "NH",
                        "NEW JERSEY": "NJ",
                        "NEW MEXICO": "NM",
                        "NEW YORK": "NY",
                        "NORTH CAROLINA": "NC",
                        "NORTH DAKOTA": "ND",
                        "OHIO": "OH",
                        "OKLAHOMA": "OK",
                        "OREGON": "OR",
                        "PENNSYLVANIA": "PA",
                        "RHODE ISLAND": "RI",
                        "SOUTH CAROLINA": "SC",
                        "SOUTH DAKOTA": "SD",
                        "TENNESSEE": "TN",
                        "TEXAS": "TX",
                        "UTAH": "UT",
                        "VERMONT": "VT",
                        "VIRGINIA": "VA",
                        "WASHINGTON": "WA",
                        "WEST VIRGINIA": "WV",
                        "WISCONSIN": "WI",
                        "WYOMING": "WY",
                        "ALA.": "AL",
                        "ALASKA": "AK",
                        "ARIZ.": "AZ",
                        "ARK.": "AR",
                        "CALIF.": "CA",
                        "COLO.": "CO",
                        "CONN.": "CT",
                        "DEL.": "DE",
                        "FLA.": "FL",
                        "GA.": "GA",
                        "HAWAII": "HI",
                        "IDAHO": "ID",
                        "ILL.": "IL",
                        "IND.": "IN",
                        "IOWA": "IA",
                        "KANS.": "KS",
                        "KY.": "KY",
                        "LA.": "LA",
                        "MAINE": "ME",
                        "MD.": "MD",
                        "MASS.": "MA",
                        "MICH.": "MI",
                        "MINN.": "MN",
                        "MISS.": "MS",
                        "MO.": "MO",
                        "MONT.": "MT",
                        "NEB. OR NEBR.": "NE",
                        "NEV.": "NV",
                        "N.H.": "NH",
                        "N.J.": "NJ",
                        "N.MEX.": "NM",
                        "N.Y.": "NY",
                        "N.C.": "NC",
                        "N.DAK.": "ND",
                        "OHIO": "OH",
                        "OKLA.": "OK",
                        "ORE. OR OREG.": "OR",
                        "PA.": "PA",
                        "R.I.": "RI",
                        "S.C.": "SC",
                        "S.DAK.": "SD",
                        "TENN.": "TN",
                        "TEX. OR TEXAS": "TX",
                        "UTAH": "UT",
                        "VT.": "VT",
                        "VA.": "VA",
                        "WASH.": "WA",
                        "W.VA.": "WV",
                        "WIS. OR WISC.": "WI",
                        "WYO.": "WY"}
